#!/bin/sh

set -e

if [ "x$COSMOS_VERBOSE" = "xy" ]; then
   args="--verbose --show_diff"
else
   args="--logdest=syslog"
fi

if [ -f /usr/bin/puppet ] && [ -d /etc/puppet/manifests ]; then
   find /etc/puppet/manifests -name \*.pp | while read -r m; do
      test "x$COSMOS_VERBOSE" = "xy" && echo "$0: Applying Puppet manifest $m"
      puppet apply $args $m
   done

   PUPPET_REPORTS_DIR='/var/lib/puppet/reports'
   if [ -d "${PUPPET_REPORTS_DIR}" ]; then
       find "${PUPPET_REPORTS_DIR}" -type f -mtime +10 -print0 | xargs -0 rm -f
   fi
fi
