#!/bin/bash

if [[ -f /var/run/reboot-required && -f /etc/cosmos-automatic-reboot ]]; then
	if [[ $AUTOMATIC_COSMOS ]]; then
		echo "$0: Would have rebooted because /var/run/reboot-required exists, if this was an automatic run"
		exit 0
	fi

	sleep=60

	# Perform an emerg syslog to allow any logged in users to remove the file and prevent a reboot.
    logger -p local0.emerg -i -t cosmos-automatic-reboot "Rebooting automatically in $sleep seconds (if /var/run/reboot-required still exists)"
    sleep $sleep
    if [ -f /var/run/reboot-required ]; then
		logger -p local0.crit -i -t cosmos-automatic-reboot "Rebooting automatically"
		reboot
    fi
fi
